FROM tensorflow/tensorflow:2.8.0rc0-gpu-jupyter
ADD motd /etc/motd
WORKDIR /app
ADD docker-requirements.txt .
RUN apt -q update && apt -qy install nodejs && \
    pip install -r docker-requirements.txt && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*

EXPOSE 8888

CMD jupyter-lab --allow-root --ip=0.0.0.0 --no-browser
