FROM gcr.io/kaggle-gpu-images/python

EXPOSE 8888
ENV SHELL=/bin/bash

ADD docker-requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt
EXPOSE 8888
ENV SHELL=/bin/bash

ADD jupyter.sh ./
CMD ./jupyter.sh
